### ISSUE TITLE
Upload files with unicode filenames

### ISSUE THREAD

**Issue by vrypan** [longaccess/bigstash-python#19]
Even after vrypan@a05e4bd092e5ff1110c9c102e3da0686ecabc2bc, `bgst put` crashes when uploading files with names in uff-8.

Sample output 

```
Uploading 28720-UKE6LX..
ERROR:bigstash.upload:error
Traceback (most recent call last):
  File "/Users/vrypan/.virtualenvs/bigstash-python/lib/python2.7/site-packages/BigStash/upload.py", line 178, in bgst_put
    callback=cb)
  File "/Users/vrypan/.virtualenvs/bigstash-python/lib/python2.7/site-packages/boto3/s3/transfer.py", line 588, in upload_file
    self._multipart_upload(filename, bucket, key, callback, extra_args)
  File "/Users/vrypan/.virtualenvs/bigstash-python/lib/python2.7/site-packages/boto3/s3/transfer.py", line 684, in _multipart_upload
    uploader.upload_file(filename, bucket, key, callback, extra_args)
  File "/Users/vrypan/.virtualenvs/bigstash-python/lib/python2.7/site-packages/boto3/s3/transfer.py", line 352, in upload_file
    filename, '/'.join([bucket, key]), e))
S3UploadFailedError: Failed to upload /Users/vrypan/\u03a4\u03bf ... \u03bd.mp3: 'ascii' codec can't encode characters in position 21-22: ordinal not in range(128)
```

**Comment by kouk** [comment]
This has been fixed in https://github.com/longaccess/bigstash-python/commit/a820a5507fbd0f5293758bf51c5e4794647644ca (and included in latest release)
