### ISSUE TITLE
OSX 10 Missing Module

### ISSUE THREAD

**Issue by jaxgeller** [longaccess/bigstash-python#23]
Hello, I installed via pip and keep getting this error.

```
Traceback (most recent call last):
  File "/usr/local/bin/bgst", line 9, in <module>
    load_entry_point('bigstash==1.2', 'console_scripts', 'bgst')()
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2345, in load
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/usr/local/lib/python2.7/site-packages/BigStash/upload.py", line 45, in <module>
    from boto3.s3.transfer import S3Transfer, TransferConfig
  File "/usr/local/lib/python2.7/site-packages/boto3/s3/transfer.py", line 133, in <module>
    from concurrent import futures
ImportError: No module named concurrent
```

Using pip, I installed `futures`, and this seemed to solve the problem. I'm not a python dev, but perhaps you just need to put the futures module in the requirements?  Am I missing anything else?  

Overall the CLI looks great and I'm looking forward to using it. Thanks!

**Comment by vrypan** [comment]
@jaxgeller Could you share the output of `pip list`?

**Comment by kouk** [comment]
@jaxgeller thanks for the report. We believe the problem is due to an incompatibility between some versions of pip and a package we list as a dependency (boto3). I have made a new version of our package available, listing the dependency in a different way, so if you install via `pip install --upgrade bigstash` it should work now out of the box.

**Comment by jaxgeller** [comment]
Awesome, thanks guys!

**Comment by kouk** [comment]
Boto3 Upstream fixed this: https://github.com/boto/boto3/issues/127
